### PR TITLE
Feature/dx 617 dx 618 omg and separator fix

### PR DESCRIPTION
**Pull request by W3stside**
Separator fix: https://gnosisltd.atlassian.net/browse/DX-618
Add OMG Token to Prod Main/Rinkeby: https://gnosisltd.atlassian.net/browse/DX-617

### CODE REVIEW

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr394--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr394--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr394--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr394--dxreact.review.gnosisdev.com

**Review by Velenir — APPROVED** [review]

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr394--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr394--dxreact.review.gnosisdev.com

**Pull request merged**
