### PR TITLE
Add public dir with google console validation html page

### PR DESCRIPTION
**Pull request by anxolin**

### CODE REVIEW

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr380--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr380--dxreact.review.gnosisdev.com

**Review by Velenir — APPROVED** [review]

**Comment by W3stside** [comment]
@anxolin `1.0.5` or no?

**Comment by anxolin** [comment]
Up to you, if it's possible it would be good to have it, but it can wait for next release.

**Pull request merged**
