### PR TITLE
Feature/app cleanup

### PR DESCRIPTION
**Pull request by W3stside**
Clean up of old dead files and movement of paths

* Claim modal waits appropriately

### CODE REVIEW

**Review by Velenir — APPROVED** [review]
Yay for no more legacy code!

**Comment by anxolin** [comment]
Nice to see some legacy code gone!

Are we done are we plan more spring cleaning?

**Comment by W3stside** [comment]
@anxolin I think this cleanup is done - will merge this into `develop`

**Comment by anxolin** [comment]
Perfect!

**Pull request merged**
