### PR TITLE
added date checker for DE unblock in CET time

### PR DESCRIPTION
**Pull request by W3stside**
Checks in app load (not polled - should it be?) whether `Date.now()` is between unlock and lock date for dxDAO mgn thing. 

_I know_ it's not super safe to use `Date.now()` but I honestly think it's fine. Up to suggestions tho!

### CODE REVIEW

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr454--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr454--dxreact.review.gnosisdev.com

**Comment by Velenir** [comment]
Getting timestamp from blockchain would of course be the safest, but I wouldn't want to rely on web3 being connected or even available at the time.

A kinda reliable but hacky way would be:
```
const {headers} = await fetch('http://google.com' or about anywhere you can trust to have real timestamp')
const now = new Date(headers.date)
```

**Comment by Velenir** [comment]
Try same-origin request
```
(await fetch(location.origin,{mode:'same-origin', method:'HEAD'})).headers.get('date')
```

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr454--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr454--dxreact.review.gnosisdev.com

**Review by Velenir — APPROVED** [review]

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr454--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr454--dxreact.review.gnosisdev.com

**Pull request merged**
