### PR TITLE
Release/1.2.0

### PR DESCRIPTION
**Pull request by W3stside**
# v1.2.0

Stuff that isn't the same as last time's stuff:
#### Bug Fixes:
- [x] Disclaimer network change works now
- [x] Rando display stuff
- [x] Site title

#### Feature-ish
- [x] 500$ USD sell order limit
- [x] Comma/period separator in selling amt
- [x] Coinbase pave over 5000
- [x] Less polltime (horrible fix for Infura hatred)

### CODE REVIEW

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr399--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr399--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr399--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr399--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr399--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr399--dxreact.review.gnosisdev.com

**Review by Velenir — APPROVED** [review]

**Pull request merged**
