### PR TITLE
with addition of MGN lock

### PR DESCRIPTION
**Pull request by Velenir**
`/#/mgn` MGN lock / unlock page

### CODE REVIEW

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr500--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr500--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr500--dxreact.review.gnosisdev.com

**Comment by anxolin** [comment]
Nice!

I would review 3 small details that we can confirm with @christianee. 

1) Should we need change this link to point to the new page:

image

2) Can we make this real links:
image

3) Review this name:
image

Maybe "Lock/Unlock MGN". Also I would make it the second or third item in the menu.


WDYT?

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr500--dxreact.review.gnosisdev.com

**Comment by Velenir** [comment]
I'm happy to change whatever, but let's have @christianee input on this first

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr500--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr500--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr500--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr500--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr500--dxreact.review.gnosisdev.com

**Review by anxolin — APPROVED** [review]

**Pull request merged**
