### PR TITLE
Hotfix-Feature/Cookie-Content-Access-With-No-Provider

### PR DESCRIPTION
**Pull request by W3stside**
### Hotfix-Feature/Cookie-Content-Access-With-No-Provider

_Highlight:_ `AppBypass` that allows users to nav to certain pages without loading Wallet logic

a. Styling issues fixed
b. Created "dumb" Header option

### CODE REVIEW

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr408--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr408--dxreact.review.gnosisdev.com

**Comment by Velenir** [comment]
Interesting idea with `appLoadBypass`
First I thought it would break on some transitions, but it doesn't!

**Review by Velenir — APPROVED** [review]

**Comment by Velenir** [comment]
`hotfix` to `develop`?

**Comment by W3stside** [comment]
i think it's more a feature at this point

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr408--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr408--dxreact.review.gnosisdev.com

**Pull request merged**
