### PR TITLE
Fix/disclaimer misc

### PR DESCRIPTION
**Pull request by W3stside**
Disclaimer logic fixes

1. Disclaimer name >> Verification

2. Simplification of Disclaimer + Terms component

### CODE REVIEW

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr410--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr410--dxreact.review.gnosisdev.com

**Review by Velenir — APPROVED** [review]

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr410--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr410--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr410--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr410--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr410--dxreact.review.gnosisdev.com

**Pull request merged**
