### PR TITLE
Contracts/tests/internal functions

### PR DESCRIPTION
**Pull request by Velenir**
Tests for internal functions. Via a contract inheriting from `DutchExchange`

### CODE REVIEW

**Comment by W3stside** [comment]
@Velenir can you change the base branch to `DX-2.0-No-Frontend` please?

**Comment by josojo** [comment]
like the way, you set up the tests with separate deployment script, contract inheritance and a  lot of helper functions.

**Comment by W3stside** [comment]
@Velenir is this finito?

**Comment by Velenir** [comment]
Soon, need a couple more tests.

**Comment by W3stside** [comment]
@Velenir looks great works great, merge

**Review by W3stside — APPROVED** [review]

**Pull request merged**
