### PR TITLE
Hotfix/1.0.5

### PR DESCRIPTION
**Pull request by W3stside**
Fixes:
1. DX-589: wrong WETH address in mainnet
2. Tentative feature: wallet change + icons for clarity

Dev-Ops side:
1. PR deployments

### CODE REVIEW

**Review by Velenir — APPROVED** [review]
Great! Lest's get it released

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr377--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr377--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr377--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr377--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr377--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr377--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr377--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr377--dxreact.review.gnosisdev.com

**Pull request merged**
