### PR TITLE
Release/2.4.0

### PR DESCRIPTION
**Pull request by W3stside**
## Change log

1. Added KNC
2. Added POOL link in Hamburger Menu
3. Restructured where Token info is in project FS
4. Updated TnC's to May 2019 revision

TODOs left
- [x] Update verification to new version fixing: tickmark bug + default analytics unchecked

### CODE REVIEW

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr491--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr491--dxreact.review.gnosisdev.com

**Review by Velenir — APPROVED** [review]
Looks good. KNC also looks good. Is it the only token with its name in the svg?

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr491--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr491--dxreact.review.gnosisdev.com

**Comment by anxolin** [comment]
Yes, I think we should add just the logo, what do you think?

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr491--dxreact.review.gnosisdev.com

**Comment by W3stside** [comment]
@anxo @Velenir logo updated

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr491--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr491--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr491--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr491--dxreact.review.gnosisdev.com

**Pull request merged**
