### PR TITLE
PR deployments

### PR DESCRIPTION
**Pull request by luarx**
Configure PR deployments

### CODE REVIEW

**Comment by W3stside** [comment]
i was like who tf is this haha. hey man!

**Comment by anxolin** [comment]
Hahah, thx Raul, we'll merge the PR as soon as we finalise the production version

**Comment by gnosis-info** [comment]
Comment test

**Comment by gnosis-info** [comment]
Comment test

**Comment by gnosis-info** [comment]
Comment test

**Comment by gnosis-info** [comment]
Comment test 2

**Comment by gnosis-info** [comment]
Comment test 2

**Comment by gnosis-info** [comment]
Comment test 2

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr373--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr373--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr373--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr373--dxreact.review.gnosisdev.com

**Comment by W3stside** [comment]
closing as already merged - dupe

**Comment by luarx** [comment]
It's not merged yet

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr373--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr373--dxreact.review.gnosisdev.com

**Pull request merged**
