### PR TITLE
Feature/enhanced error handling

### PR DESCRIPTION
**Pull request by W3stside**
### Enhanced Error Handling

1. Errors in `contracts.ts` shown in WalletChooser to allow easy re-loading of app
2. API `force` param to reload API if necessary
3. `setProvider` `undefined` `provider` check - allowing app to throw if provider fails to init. Stops unnecessary unload of `Error` messages to user

To test error in `setProvider`:
1. Uncomment lines `140 && 141` and refresh a couple times
2. add a `throw 'Some error'` inside the `init` function of `api/contracts.ts`

### CODE REVIEW

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr440--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr440--dxreact.review.gnosisdev.com

**Review by Velenir — APPROVED** [review]

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr440--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr440--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr440--dxreact.review.gnosisdev.com

**Pull request merged**
