### PR TITLE
Hotfix/1.0.6

### PR DESCRIPTION
**Pull request by anxolin**
- Add landing page
- Add mainnet token pairs (not done yet): WETH-DAI, WETH-MKR, DAI-MKR

We already have to add the markets specified in above. The addresses can be checked here: https://dutchx.d.exchange/api/docs/#!/markets/getMarkets

### CODE REVIEW

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr386--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr386--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr386--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr386--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr386--dxreact.review.gnosisdev.com

**Review by W3stside — APPROVED** [review]
ready

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr386--dxreact.review.gnosisdev.com

**Pull request merged**
