### PR TITLE
10k sell limit

### PR DESCRIPTION
**Pull request by Velenir**
Sets sell limit to 10K USD for mainnet

### CODE REVIEW

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr481--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr481--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr481--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr481--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr481--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr481--dxreact.review.gnosisdev.com

**Review by W3stside — APPROVED** [review]

**Pull request merged**
