### PR TITLE
Reduced website size by 75% 

### PR DESCRIPTION
**Pull request by denisgranha**
by removing big useless params from truffle artifacts

### CODE REVIEW

**Review by anxolin — APPROVED** [review]

**Comment by W3stside** [comment]
Do not merge until `ethereum-abi` missing module error from travis build is resolved

**Review by W3stside — CHANGES_REQUESTED** [review]
fix `ethereum-abi` js travis build error

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr469--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr469--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr469--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr469--dxreact.review.gnosisdev.com

**Comment by W3stside** [comment]
closing in favour of #497

**Pull request closed without merging**
