### PR TITLE
Dx-635-637/Confirmation-Screen-Change + Input-Limit

### PR DESCRIPTION
**Pull request by Velenir**
DX-637: Limits input for sell amount to ≈ 500 usd

+

Dx-635: Confirmation screen changes

### CODE REVIEW

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr401--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr401--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr401--dxreact.review.gnosisdev.com

**Comment by ghost** [comment]
Travis automatic deployment:
 https://pr401--dxreact.review.gnosisdev.com

**Comment by W3stside** [comment]
@Velenir can you toss the MAX_SELL_USD inside `global`?

**Review by W3stside — APPROVED** [review]
looks good to me

**Pull request merged**
